[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "14"

[build.processing]
  # Allow serverless functions to be processed
  node_bundler = true

[[plugins]]
  package = "@netlify/plugin-functions"